### ISSUE TITLE
Please provide a mechanism to handle errors connecting to KLF

### ISSUE THREAD

**Issue by klessed** [ChrisHanuta/node-red-contrib-velux#15]
When the KLF-200 does not accept incoming connections I would like to take action within my flows 
-> send email or push notifications, restart the klf by switching  the outlet off and on again, ...

At the moment there is just an error message in the debug pane (eg "Start timeout reset the klf-200 please")

One mechanism I can think of:
register these connection issues in the status of all velux nodes. With the status node one can take action if the status turns to red.

**Comment by PLCHome** [comment]
Make a change on source and a pull request. 
I just host the node and don't use it anymore. 


The problem lies with Velux. If the connection breaks down twice, there is no longer a receiver. 

My tip: Take a Inject and Velux API to send a reset one to two times a day.

If I post here that I'm not interested, 10 come by who want to host the component, and not maintain it either.
