### ISSUE TITLE
Support for 3LG E01 Gateway

### ISSUE THREAD

**Issue by Tazintosh** [ChrisHanuta/node-red-contrib-velux#5]
Hi @PLCHome, any plan to support the latest 3LG E01 Velux Gateway?
Or do you know some existing Node-RED port I would have missed?

**Comment by PLCHome** [comment]
I'm sorry, I will not really implement anything.
3LG E01/NXG01E --> KIX300

1. The support for the KLF200 I built because I bought the device and there was no good node.

2. I have no idea if the KIX300 even has an open interface. He is only made for the cloud and mobile app. I believe that there is no external API is available. That means you can control the blinds on mobile, that's it. Does the KIX300 even have a direct HTTP access in the network over the IP address?
Communication with the KIX300 home automation system is only possible via the KLF200 or KLF50 via IO Homecontrol.

**Comment by Tazintosh** [comment]
Indeed, nothing when requesting http://my_gateway_ip
Too bad.
Thanks for your answer.

**Comment by PLCHome** [comment]
Let me know if I'm wrong
